name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Check version
      run: |
        version=$(poetry version --short)
        tag=$(echo "${{ github.ref }}" | awk '{split($0,p,"/"); print p[3]}')
        if [ "v$version" != $tag ]; then echo "Release tag and package version do not match!"; exit 1; fi;
    - name: Build and publish package
      env:
        POETRY_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry build
        poetry publish -u __token__ -p $POETRY_PYPI_TOKEN --no-interaction
